# Generated by Django 5.1.7 on 2025-03-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_converted_date_lead_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
