# Generated by Django 5.1.7 on 2025-03-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_completed_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
